// Auto-generated by @mustafaaksoy41/sharepoint-kit CLI
// Do not edit manually. Run: npx sp-generate-types --config sharepoint.config.ts


export interface Invoice {
  /** Ad */
  FileLeafRef: unknown;
  /** Başlık */
  title?: unknown;
  /** Fatura Numarası */
  Fatura_x0020_Numaras_x0131_?: unknown;
  /** Müşteri Np */
  M_x00fc__x015f_teri_x0020_Np?: unknown;
  Tutar?: unknown;
  departmentNo?: unknown;
}

export interface Employee {
  /** Başlık */
  title?: unknown;
  jobTitle?: unknown;
  Person?: unknown;
}
